services:
  Codein\eZColorPicker\FieldType\ColorPicker\Type:
    autoconfigure: false
    autowire: true
    public: true
    tags:
      - { name: ezplatform.field_type, alias: codeincolor }
      - { name: ezplatform.field_type.form_mapper.value, fieldType: codeincolor }

  codein.ezcolorpicker.fieldtype.colorpicker.type.notindexable:
    class: eZ\Publish\Core\FieldType\Unindexed
    tags:
      - { name: ezplatform.field_type.indexable, alias: codeincolor }

